### ISSUE TITLE
Enable TokenRequest API?

### ISSUE THREAD

**Issue by zer0def** [schu/kubedee#59]
Some software packages started leveraging [service account token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection), most notably - Istio. Would it be much of a bother to enable this feature as part of Kubedee's cluster deployment?

The addition of the below snippet to `kube-apiserver.service` would hopefully achieve the result, though YMMV:
```
  --service-account-api-audiences=api,vault,factors \\
  --service-account-issuer=api \\
  --service-account-signing-key-file=/etc/kubernetes/ca-key.pem \\
```

Helmfile installing Istio for replication purposes via a quick `helmfile sync`:
```
{{- $helmTimeout := default 600 (env "HELM_TIMEOUT") -}}
{{- $networkNamespace := default "network" (env "NETWORK_NAMESPACE") -}}
{{- $istioInitReleaseName := default "istio-init" (env "ISTIO_INIT_HELM_RELEASE_NAME") -}}
{{- $istioReleaseName := default "istio" (env "ISTIO_HELM_RELEASE_NAME") -}}
{{- $istioVersion := default "1.5.1" (env "ISTIO_VERSION") -}}
{{- $istioMajor := slice (splitList "." $istioVersion) 0 2 | join "." -}} 

repositories:
- name: istio{{ $istioMajor }}
  url: https://storage.googleapis.com/istio-release/releases/{{ $istioVersion }}/charts

helmDefaults:
  wait: true
  timeout: {{ $helmTimeout }}
  tillerless: false

releases:
- name: {{ $istioInitReleaseName }}
  namespace: {{ $networkNamespace }}
  chart: istio{{ $istioMajor }}/istio-init
  values:
  - certmanager:
      enabled: true
  hooks:
  - events: ["postsync"]
    command: "/bin/sh"
    args: ["-xec", "kubectl -n {{ $networkNamespace }} wait --for condition=complete --timeout {{ $helmTimeout }}s job --all && sleep 5"]
- name: {{ $istioReleaseName }}
  namespace: {{ $networkNamespace }}
  chart: istio{{ $istioMajor }}/istio
  needs:
  - {{ $networkNamespace }}/{{ $istioInitReleaseName }}
  values:
  - global:
      tag: {{ $istioVersion }}
      sds:
        enabled: true
    gateways:
      istio-ingressgateway:
        type: NodePort
        sds:
          enabled: true
```
The symptom of it not being there would be some of the Istio pods being stuck in `ContainerCreating`, because the feature is not available.

As of now, `istio-citadel` keeps crashing, so I'm probably supplying a bad trust chain in the first snippet.
